import { AboutUs, Batches, ChampionsLeague, ContactUs, Feeds, Home, Library, PrivacyPolicy, PwCenters, QuickLearning, ReferEarn, Result, Saarthi, Scholarship, Store, Study, TermsConditions, TestSeries, Upskilling, VpLive, Wallet, Yogya } from "@/assets/icons"
import GovernmentJobs from "@/assets/icons/GovernmentJobs"

export const sideNavbarOptions = [

  {
    customHeader: "Learn Online",
    menuOptions: [
      {
        title: "Home",
        icon: <Home />,
        url: process.env.PUBLIC_BASE_PATH,
        isActive: true,
        isNew: false,
        badge: "",
        isEnabled: true,
        configName: 'isHomePageEnabled',
        subMenuOption: [],
      },
      {
        title: "Study",
        icon: <Study />,
        url: "/study",
        isActive: true,
        isNew: true,
        badge: "1",
        isEnabled: true,
        configName: 'isStudyPageEnabled',
        subMenuOption: [],
      },
      {
        title: "Quick Learning",
        icon: <QuickLearning />,
        url: '/batches/study/micro-learning',
        isActive: false,
        external: false,
        isNew: false,
        isEnabled: true,
        configName: 'isMicroLearningEnabled',
        badge: "",
        subMenuOption: [],

      },
      {
        title: "Saarthi",
        icon: <Saarthi />,
        url: '/saarthi',
        isActive: false,
        isEnabled: true,
        configName: 'isSarthiEnabled',
        badge: '',
        subMenuOption: [
          {
            title: "Today's Classes",
            url: "/todayclasses",
            isActive: false,
            isNew: false,
            badge: "",
            isEnabled: true,
            configName: '',
          },
          {
            title: "Khazana",
            url: "/khazana",
            isActive: false,
            isNew: false,
            isEnabled: true,
            configName: '',

          },
          {
            title: "Library",
            url: "/library2",
            isActive: false,
            isNew: false,
            isEnabled: true,
            configName: '',
          },
          {
            title: "Announcements",
            url: "/announcements",
            isActive: false,
            isNew: false,
            isEnabled: true,
            configName: '',
          },
        ]
      },
      {
        title: "Library",
        icon: <Library />,
        url: '/library',
        isActive: false,
        isEnabled: true,
        configName: 'isLibraryEnabled',
        isNew: true,
        badge: '',

      },
    ],
  },
  {
    customHeader: "Study Packs",
    menuOptions: [
      {
        title: "Batches",
        icon: <Batches />,
        url: '/batches',
        isActive: true,
        isEnabled: true,
        configName: 'isBatchPageEnabled',
        subMenuOption: [],

      },
      {
        title: "Test Series",
        icon: <TestSeries />,
        url: '/test-series',
        isActive: false,
        isEnabled: true,
        configName: 'isTestSeriesEnabled',
        badge: "1",
        subMenuOption: [],

      },
      {
        title: "Scholarship",
        icon: <Scholarship />,
        url: '/pw-scholarship',
        isActive: false,
        external: false,
        isNew: false,
        isEnabled: true,
        configName: 'isScholarshipEnabled',
        subMenuOption: [],
      },
      {
        title: 'Apply for Grant',
        icon: <Yogya />,
        url: '/yogya',
        isActive: true,
        isNew: false,
        badge: "",
        isEnabled: true,
        configName: 'isYogyaEnabled',
        subMenuOption: [],
      },
      {
        title: 'Government jobs',
        icon: <GovernmentJobs />,
        url: '/job-alert',
        isActive: true,
        isNew: false,
        badge: "",
        isEnabled: true,
        configName: 'isGovtJobEnabled',
        subMenuOption: [],
      },

    ],
  },
  {
    customHeader: "Offline",
    menuOptions: [
      {
        title: 'PW Centres',
        icon: <PwCenters />,
        url: '/pw-centres',
        isActive: false,
        isNew: false,
        isEnabled: true,
        configName: 'isPWCentersEnabled',
        subMenuOption: [],
      },
      {
        title: 'VP Live',
        icon: <VpLive />,
        url: '/vp-live',
        isActive: true,
        isNew: false,
        badge: "",
        isEnabled: true,
        configName: 'isVpLiveEnabled',
        subMenuOption: [],
      },
      {
        title: 'PW Champions League',
        icon: <ChampionsLeague />,
        url: '/school-contact-program',
        isActive: true,
        isNew: false,
        badge: "",
        isEnabled: true,
        configName: 'isPwChampionshipEnabled',
        subMenuOption: [],
      },

    ],
  },
  {
    customHeader: "Explore PW",
    menuOptions: [
      {
        title: "Upskilling",
        icon: <Upskilling />,
        url: "/upskilling",
        isActive: false,
        external: false,
        isNew: false,
        isEnabled: true,
        configName: '',
        subMenuOption: [],
      },
      {
        title: "Store",
        icon: <Store />,
        url: 'https://store.pw.live/authenticate',
        isActive: false,
        isEnabled: true,
        configName: '',
        external: true,
        isNew: false,
        subMenuOption: [],
      },
      {
        title: "Results",
        icon: <Result />,
        url: '/results',
        isActive: false,
        isEnabled: true,
        configName: 'isOurResultsEnabled',
        subMenuOption: [],
      },
      {
        title: "Feeds",
        icon: <Feeds />,
        url: '/feeds',
        isActive: false,
        isEnabled: true,
        configName: 'isFeedsEnabled',
        subMenuOption: [],
      },
      {
        title: 'About us',
        icon: <AboutUs />,
        url: '/about-us',
        isActive: true,
        isNew: false,
        badge: "",
        isEnabled: true,
        configName: 'isAboutUsEnabled',
        subMenuOption: [],
      },
    ],
  },
  {
    customHeader: "More",
    menuOptions: [
      {
        title: "Refer & Earn",
        icon: <ReferEarn />,
        url: '/referral-new',
        isActive: false,
        isEnabled: true,
        configName: 'isReferAndEarnEnabled',
        subMenuOption: [],

      },
      {
        title: "Wallet",
        icon: <Wallet />,
        url: '/wallet',
        isActive: false,
        isEnabled: true,
        configName: 'isWalletEnabled',
        subMenuOption: [],

      },
      {
        title: "Contact Us",
        icon: <ContactUs />,
        url: '/contact-us',
        isActive: false,
        isEnabled: true,
        configName: 'isContactUsEnabled',
        subMenuOption: [],
      },
      {
        title: "Terms & Conditions",
        icon: <TermsConditions />,
        url: '/termsandconditions',
        isActive: false,
        isEnabled: false,
        configName: 'isTandCEnabled',
        subMenuOption: [],

      },
      {
        title: "Privacy Policy",
        icon: <PrivacyPolicy />,
        url: "/privacypolicy",
        isActive: false,
        isNew: false,
        isEnabled: true,
        subMenuOption: [],
      },
    ],
  },

]



